filter:
  excluded_paths: [Tests/*]

build:
  environment:
    php:
      version: 7.2
  tests:
    override:
      -
        command: 'vendor/bin/phpunit --coverage-clover=clover.xml'
        coverage:
          file: 'clover.xml'
          format: 'php-clover'
checks:
  php:
    custom_coding_standard:
      ruleset_path: 'phpcs.xml'
